//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_dirtyconf.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirtyConf")]
  public partial class DirtyConf : global::ProtoBuf.IExtensible
  {
    public DirtyConf() {}
    
    private string _DirtyWord;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DirtyWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DirtyWord
    {
      get { return _DirtyWord; }
      set { _DirtyWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirtyConfArray")]
  public partial class DirtyConfArray : global::ProtoBuf.IExtensible
  {
    public DirtyConfArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.DirtyConf> _items = new global::System.Collections.Generic.List<dataconfig.DirtyConf>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.DirtyConf> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}