// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace cs
{
    public partial class CSPkgHead
    {
        public CSPkgHead()
        {
            Clear();
        }
        public string CmdID { get; set; }

        public uint checkID { get; set; }

        public uint MsgSeqID { get; set; }

        public uint NotifyMsgSeqID { get; set; }

        /// <summary> 低 4 位表示加密类型 @see EnmEncryptType; 高 4 位表示压缩类型 @see EnmCompressType</summary>
        public uint EncryptCompressType { get; set; }


        public void Clear()
        {
            CmdID = "";
            MsgSeqID = 0;
            NotifyMsgSeqID = 0;
            EncryptCompressType = 0;
        }
    }

    public partial class CSPKG
    {
        public CSPKG()
        {
            Clear();
        }
        public global::cs.CSPkgHead Head { get; set; }

        public byte[] Body { get; set; }


        public void Clear()
        {
            if (Head != null)
            {
                Head.Clear();
            }
        }
    }

}
