//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DownloadCachesMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DownloadCachesMgr), typeof(Singleton<DownloadCachesMgr>));
		L.RegFunction("LoadImage", LoadImage);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			DownloadCachesMgr obj = (DownloadCachesMgr)ToLua.CheckObject(L, 1, typeof(DownloadCachesMgr));
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<int,UnityEngine.Texture2D> arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (System.Action<int,UnityEngine.Texture2D>)ToLua.CheckObject(L, 3, typeof(System.Action<int,UnityEngine.Texture2D>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(System.Action<int,UnityEngine.Texture2D>), func) as System.Action<int,UnityEngine.Texture2D>;
			}

			obj.LoadImage(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

