//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingleWebWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingleWeb), typeof(Singleton<SingleWeb>));
		L.RegFunction("InitWebPage", InitWebPage);
		L.RegFunction("GetDicObj", GetDicObj);
		L.RegFunction("DestroyDicObj", DestroyDicObj);
		L.RegFunction("DestroyAll", DestroyAll);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("dic", get_dic, set_dic);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitWebPage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(SingleWeb), typeof(string)))
			{
				SingleWeb obj = (SingleWeb)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				WebPage o = obj.InitWebPage(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 6 && TypeChecker.CheckTypes(L, 1, typeof(SingleWeb), typeof(string), typeof(int), typeof(int), typeof(int), typeof(int)))
			{
				SingleWeb obj = (SingleWeb)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				int arg3 = (int)LuaDLL.lua_tonumber(L, 5);
				int arg4 = (int)LuaDLL.lua_tonumber(L, 6);
				WebPage o = obj.InitWebPage(arg0, arg1, arg2, arg3, arg4);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SingleWeb.InitWebPage");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDicObj(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SingleWeb obj = (SingleWeb)ToLua.CheckObject(L, 1, typeof(SingleWeb));
			string arg0 = ToLua.CheckString(L, 2);
			WebPage o = obj.GetDicObj(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyDicObj(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SingleWeb obj = (SingleWeb)ToLua.CheckObject(L, 1, typeof(SingleWeb));
			string arg0 = ToLua.CheckString(L, 2);
			obj.DestroyDicObj(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SingleWeb obj = (SingleWeb)ToLua.CheckObject(L, 1, typeof(SingleWeb));
			obj.DestroyAll();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dic(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SingleWeb obj = (SingleWeb)o;
			System.Collections.Generic.Dictionary<string,WebPage> ret = obj.dic;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index dic on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dic(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SingleWeb obj = (SingleWeb)o;
			System.Collections.Generic.Dictionary<string,WebPage> arg0 = (System.Collections.Generic.Dictionary<string,WebPage>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,WebPage>));
			obj.dic = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index dic on a nil value" : e.Message);
		}
	}
}

