//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class XyhyGlobalWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(XyhyGlobal), typeof(System.Object));
		L.RegFunction("New", _CreateXyhyGlobal);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("IsReleaseVersion", get_IsReleaseVersion, null);
		L.RegVar("IsLoadAssetBundle", get_IsLoadAssetBundle, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateXyhyGlobal(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				XyhyGlobal obj = new XyhyGlobal();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: XyhyGlobal.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsReleaseVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, XyhyGlobal.IsReleaseVersion);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsLoadAssetBundle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, XyhyGlobal.IsLoadAssetBundle);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

