// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace cs
{
    /// <summary>Actor属性字段key</summary>
    public enum ActorAttrEnum
    {
        U_ACTOR_BASE_STRENGTH_ATTR = 1,
        /// <summary>力量</summary>
        U_ACTOR_BASE_INTERFORCE_ATTR = 2,
        /// <summary>内力</summary>
        U_ACTOR_BASE_ENDURANCE_ATTR = 3,
        /// <summary>耐力</summary>
        U_ACTOR_BASE_SPIRIT_ATTR = 4,
        /// <summary>灵力</summary>
        U_ACTOR_BASE_AGILITY_ATTR = 5,
        /// <summary>身法</summary>
        U_ACTOR_BASE_MAX_HP_ATTR = 6,
        /// <summary>玩家最大血量</summary>
        U_ACTOR_BASE_MAX_MP_ATTR = 7,
        /// <summary>玩家最大真气值</summary>
        U_ACTOR_BASE_HP_SPEED_ATTR = 8,
        /// <summary>玩家血量恢复速度</summary>
        U_ACTOR_BASE_MP_SPEED_ATTR = 9,
        /// <summary>玩家真气每秒恢复速度</summary>
        U_ACTOR_BASE_OUT_ATTACK_ATTR = 10,
        /// <summary>外功攻击力</summary>
        U_ACTOR_BASE_OUT_DEFENCE_ATTR = 11,
        /// <summary>外功防御力</summary>
        U_ACTOR_BASE_INTER_ATTACK_ATTR = 12,
        /// <summary>内攻攻击力</summary>
        U_ACTOR_BASE_INTER_DEFENCE_ATTR = 13,
        /// <summary>内功防御力</summary>
        U_ACTOR_BASE_FIRE_ATTACK_ATTR = 14,
        /// <summary>火系攻击力</summary>
        U_ACTOR_BASE_FIRE_DEFENCE_ATTR = 15,
        /// <summary>火系防御力</summary>
        U_ACTOR_BASE_WATER_ATTACK_ATTR = 16,
        /// <summary>水系攻击力</summary>
        U_ACTOR_BASE_WATER_DEFENCE_ATTR = 17,
        /// <summary>水系防御力</summary>
        U_ACTOR_BASE_EARTH_ATTACK_ATTR = 18,
        /// <summary>土系攻击力</summary>
        U_ACTOR_BASE_EARTH_DEFENCE_ATTR = 19,
        /// <summary>土系防御力</summary>
        U_ACTOR_BASE_WIND_ATTACK_ATTR = 20,
        /// <summary>风系攻击力</summary>
        U_ACTOR_BASE_WIND_DEFENCE_ATTR = 21,
        /// <summary>风系防御力</summary>
        U_ACTOR_BASE_CRITICALHITHP_ATTR = 22,
        /// <summary>会心一击伤害</summary>
        U_ACTOR_BASE_CRITICALHIT_ATTR = 23,
        /// <summary>会心一击</summary>
        U_ACTOR_BASE_CRITICALHITPA_ATTR = 24,
        /// <summary>会心一击几率</summary>
        U_ACTOR_BASE_MODE_ID_ATTR = 25,
        /// <summary>模型类型</summary>
        U_ACTOR_BASE_GRADE_ATTR = 26,
        /// <summary>玩家等级信息</summary>
        U_ACTOR_BASE_SEX_ATTR = 27,
        /// <summary>性别</summary>
        U_ACTOR_BASE_TILTE_ATTR = 28,
        /// <summary>当前称号id</summary>
        U_ACTOR_WEAPON_TYPE = 29,
        /// <summary>武器类型</summary>
        U_ACTOR_CUR_EXP = 30,
        /// <summary>经验</summary>
        U_ACTOR_MONEY_GOLD = 31,
        /// <summary>金元宝</summary>
        U_ACTOR_MONEY_SILVER = 32,
        /// <summary>银元宝</summary>
        U_ACTOR_MONEY_COPPER = 33,
        /// <summary>铜钱</summary>
        U_ACTOR_MONEY_HONORVALUE = 34,
        /// <summary>荣誉值</summary>
        U_ACTOR_MONEY_CHIVALRYVALUE = 35,
        /// <summary>狭义值</summary>
        U_ACTOR_MONEY_FACTIONVALUE = 36,
        /// <summary>帮贡值</summary>
        U_ACTOR_BASE_CURR_HP_ATTR = 37,
        /// <summary>玩家当前血量</summary>
        U_ACTOR_BASE_CURR_MP_ATTR = 38,
        /// <summary>玩家当前真气值</summary>
        U_ACTOR_BASE_SAVVY_ATTR = 39,
        /// <summary>玩家悟性</summary>
        U_ACTOR_BASE_CAMP_ATTR = 40,
        /// <summary>玩家阵营</summary>
        U_ACTOR_MOVE_SPEED = 41,
        /// <summary>玩家移动速度</summary>
        U_NPC_BATI_VALUE = 42,
        /// <summary>NPC霸体值</summary>
        U_NPC_BATI_MAX_VALUE = 43,
        /// <summary>NPC霸体最大值</summary>
        U_NPC_CURR_STATE = 44,
        /// <summary>NPC当前状态</summary>
        U_ACTOR_FIGHTING_VALUE = 45,
        /// <summary>玩家战斗力</summary>
        U_PLAYER_SWORD_VALUE = 46,
        /// <summary>剑系剩余技能点数</summary>
        U_PLAYER_KNIFE_VALUE = 47,
        /// <summary>抢系剩余点数</summary>
        U_PLAYER_FIST_VALUE = 48,
        /// <summary>拳系剩余点数</summary>
        U_PLAYER_RESPACT_NUM = 49,
        /// <summary>玩家洗点次数</summary>
        U_ACTOR_WALK_SPEED = 50,
        /// <summary>走路速度</summary>
        U_PLAYER_ATTR_ANGER = 51,
        /// <summary>玩家怒气值</summary>
        U_PLAYER_PK_MODE = 52,
        /// <summary>玩家pk模式</summary>
        U_PLAYER_BOW_VALUE = 53,
        /// <summary>弓剩余技能点</summary>
        U_PLAYER_ALL_SKILL_POINT_VALUE = 54,
        /// <summary>玩家所有技能点</summary>
        U_PLAYER_FACTION_NAME_VALUE = 55,
        /// <summary>玩家所属帮会名</summary>
        U_PLAYER_HELP_COIN_VALUE = 56,
        /// <summary>玩家互助币</summary>
        U_PLAYER_SAN_QIU_DAN_TIME_VALUE = 57,
        /// <summary>玩家三秋丹剩余时间</summary>
        U_PLAYER_WISH_POOL_TIME = 58,
        /// <summary>玩家上次进行许愿池时间(单次)</summary>
        U_PLAYER_CD_PER = 59,
        /// <summary>玩家身上CD百分比</summary>
        U_PLAYER_CD_VALUE = 60,
        /// <summary>玩家身上CDvalue属性影响</summary>
        U_PLAYER_SAN_QIU_DAN_NUM = 61,
        /// <summary>所需的三秋丹数量</summary>
        U_NPC_JUMP_POINT = 62,
        /// <summary> 传送阵的跳转点</summary>
        U_ACTOR_ADD_EXTRA_EXP = 63,
        /// <summary> 额外加成经验</summary>
        U_PLAYER_ANGER_STATE = 64,
        /// <summary> 怒气技能开放状态</summary>
        U_PLAYER_SHOW_ACTION = 65,
        /// <summary> 玩家动作表现状态</summary>
        U_ACTOR_THREAT_VALUE = 66,
    }


}
