-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"


local SHISANSHUITABLECONFIG = protobuf.Descriptor();
local SHISANSHUITABLECONFIG_ID_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIG_POS1_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIG_POS2_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIG_POS3_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIG_POS4_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIG_POS5_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIG_POS6_FIELD = protobuf.FieldDescriptor();
local SHISANSHUITABLECONFIGARRAY = protobuf.Descriptor();
local SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();

SHISANSHUITABLECONFIG_ID_FIELD.name = "id"
SHISANSHUITABLECONFIG_ID_FIELD.full_name = ".dataconfig.shisanshuitableconfig.id"
SHISANSHUITABLECONFIG_ID_FIELD.number = 1
SHISANSHUITABLECONFIG_ID_FIELD.index = 0
SHISANSHUITABLECONFIG_ID_FIELD.label = 2
SHISANSHUITABLECONFIG_ID_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_ID_FIELD.default_value = 0
SHISANSHUITABLECONFIG_ID_FIELD.type = 13
SHISANSHUITABLECONFIG_ID_FIELD.cpp_type = 3

SHISANSHUITABLECONFIG_POS1_FIELD.name = "pos1"
SHISANSHUITABLECONFIG_POS1_FIELD.full_name = ".dataconfig.shisanshuitableconfig.pos1"
SHISANSHUITABLECONFIG_POS1_FIELD.number = 2
SHISANSHUITABLECONFIG_POS1_FIELD.index = 1
SHISANSHUITABLECONFIG_POS1_FIELD.label = 1
SHISANSHUITABLECONFIG_POS1_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_POS1_FIELD.default_value = ""
SHISANSHUITABLECONFIG_POS1_FIELD.type = 9
SHISANSHUITABLECONFIG_POS1_FIELD.cpp_type = 9

SHISANSHUITABLECONFIG_POS2_FIELD.name = "pos2"
SHISANSHUITABLECONFIG_POS2_FIELD.full_name = ".dataconfig.shisanshuitableconfig.pos2"
SHISANSHUITABLECONFIG_POS2_FIELD.number = 3
SHISANSHUITABLECONFIG_POS2_FIELD.index = 2
SHISANSHUITABLECONFIG_POS2_FIELD.label = 1
SHISANSHUITABLECONFIG_POS2_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_POS2_FIELD.default_value = ""
SHISANSHUITABLECONFIG_POS2_FIELD.type = 9
SHISANSHUITABLECONFIG_POS2_FIELD.cpp_type = 9

SHISANSHUITABLECONFIG_POS3_FIELD.name = "pos3"
SHISANSHUITABLECONFIG_POS3_FIELD.full_name = ".dataconfig.shisanshuitableconfig.pos3"
SHISANSHUITABLECONFIG_POS3_FIELD.number = 4
SHISANSHUITABLECONFIG_POS3_FIELD.index = 3
SHISANSHUITABLECONFIG_POS3_FIELD.label = 1
SHISANSHUITABLECONFIG_POS3_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_POS3_FIELD.default_value = ""
SHISANSHUITABLECONFIG_POS3_FIELD.type = 9
SHISANSHUITABLECONFIG_POS3_FIELD.cpp_type = 9

SHISANSHUITABLECONFIG_POS4_FIELD.name = "pos4"
SHISANSHUITABLECONFIG_POS4_FIELD.full_name = ".dataconfig.shisanshuitableconfig.pos4"
SHISANSHUITABLECONFIG_POS4_FIELD.number = 5
SHISANSHUITABLECONFIG_POS4_FIELD.index = 4
SHISANSHUITABLECONFIG_POS4_FIELD.label = 1
SHISANSHUITABLECONFIG_POS4_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_POS4_FIELD.default_value = ""
SHISANSHUITABLECONFIG_POS4_FIELD.type = 9
SHISANSHUITABLECONFIG_POS4_FIELD.cpp_type = 9

SHISANSHUITABLECONFIG_POS5_FIELD.name = "pos5"
SHISANSHUITABLECONFIG_POS5_FIELD.full_name = ".dataconfig.shisanshuitableconfig.pos5"
SHISANSHUITABLECONFIG_POS5_FIELD.number = 6
SHISANSHUITABLECONFIG_POS5_FIELD.index = 5
SHISANSHUITABLECONFIG_POS5_FIELD.label = 1
SHISANSHUITABLECONFIG_POS5_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_POS5_FIELD.default_value = ""
SHISANSHUITABLECONFIG_POS5_FIELD.type = 9
SHISANSHUITABLECONFIG_POS5_FIELD.cpp_type = 9

SHISANSHUITABLECONFIG_POS6_FIELD.name = "pos6"
SHISANSHUITABLECONFIG_POS6_FIELD.full_name = ".dataconfig.shisanshuitableconfig.pos6"
SHISANSHUITABLECONFIG_POS6_FIELD.number = 7
SHISANSHUITABLECONFIG_POS6_FIELD.index = 6
SHISANSHUITABLECONFIG_POS6_FIELD.label = 1
SHISANSHUITABLECONFIG_POS6_FIELD.has_default_value = true
SHISANSHUITABLECONFIG_POS6_FIELD.default_value = ""
SHISANSHUITABLECONFIG_POS6_FIELD.type = 9
SHISANSHUITABLECONFIG_POS6_FIELD.cpp_type = 9

SHISANSHUITABLECONFIG.name = "shisanshuitableconfig"
SHISANSHUITABLECONFIG.full_name = ".dataconfig.shisanshuitableconfig"
SHISANSHUITABLECONFIG.nested_types = {}
SHISANSHUITABLECONFIG.enum_types = {}
SHISANSHUITABLECONFIG.fields = {SHISANSHUITABLECONFIG_ID_FIELD, SHISANSHUITABLECONFIG_POS1_FIELD, SHISANSHUITABLECONFIG_POS2_FIELD, SHISANSHUITABLECONFIG_POS3_FIELD, SHISANSHUITABLECONFIG_POS4_FIELD, SHISANSHUITABLECONFIG_POS5_FIELD, SHISANSHUITABLECONFIG_POS6_FIELD}
SHISANSHUITABLECONFIG.is_extendable = false
SHISANSHUITABLECONFIG.extensions = {}
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.name = "items"
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.full_name = ".dataconfig.shisanshuitableconfigArray.items"
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.number = 1
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.index = 0
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.label = 3
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.has_default_value = false
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.default_value = {}
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.message_type = SHISANSHUITABLECONFIG
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.type = 11
SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD.cpp_type = 10

SHISANSHUITABLECONFIGARRAY.name = "shisanshuitableconfigArray"
SHISANSHUITABLECONFIGARRAY.full_name = ".dataconfig.shisanshuitableconfigArray"
SHISANSHUITABLECONFIGARRAY.nested_types = {}
SHISANSHUITABLECONFIGARRAY.enum_types = {}
SHISANSHUITABLECONFIGARRAY.fields = {SHISANSHUITABLECONFIGARRAY_ITEMS_FIELD}
SHISANSHUITABLECONFIGARRAY.is_extendable = false
SHISANSHUITABLECONFIGARRAY.extensions = {}

shisanshuitableconfig = protobuf.Message(SHISANSHUITABLECONFIG)
shisanshuitableconfigArray = protobuf.Message(SHISANSHUITABLECONFIGARRAY)

--[[Another parser, for the memory reason, use plain table struct 
instead of protobuf table! Auto generated, do not edit!!]]
shisanshuitableconfig_x = {}
shisanshuitableconfig_x.__index = shisanshuitableconfig_x


--[[The class create method]]
function shisanshuitableconfig_x.New()
    local self = {}
    setmetatable(self, shisanshuitableconfig_x)
    self.items = {}
    return self
end


--[[The data parse method, input the protobuf data instance]]
function shisanshuitableconfig_x:ParseData(protobufData)
    for k, v in ipairs(protobufData.items) do 
        local item = {}
        item.id = v.id
        if v:HasField("pos1") then 
            item.pos1 = v.pos1
        end
        if v:HasField("pos2") then 
            item.pos2 = v.pos2
        end
        if v:HasField("pos3") then 
            item.pos3 = v.pos3
        end
        if v:HasField("pos4") then 
            item.pos4 = v.pos4
        end
        if v:HasField("pos5") then 
            item.pos5 = v.pos5
        end
        if v:HasField("pos6") then 
            item.pos6 = v.pos6
        end
        table.insert(self.items, item)
    end
end


--[[Get the protobuf instance]]
function shisanshuitableconfig_x:GetProtobuf()
    return shisanshuitableconfigArray()
end
