-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"


local SHOPCONFIG = protobuf.Descriptor();
local SHOPCONFIG_UID_FIELD = protobuf.FieldDescriptor();
local SHOPCONFIG_NAME_FIELD = protobuf.FieldDescriptor();
local SHOPCONFIG_TYPE_FIELD = protobuf.FieldDescriptor();
local SHOPCONFIG_ID_FIELD = protobuf.FieldDescriptor();
local SHOPCONFIG_NUMBER_FIELD = protobuf.FieldDescriptor();
local SHOPCONFIGARRAY = protobuf.Descriptor();
local SHOPCONFIGARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();

SHOPCONFIG_UID_FIELD.name = "uid"
SHOPCONFIG_UID_FIELD.full_name = ".dataconfig.ShopConfig.uid"
SHOPCONFIG_UID_FIELD.number = 1
SHOPCONFIG_UID_FIELD.index = 0
SHOPCONFIG_UID_FIELD.label = 2
SHOPCONFIG_UID_FIELD.has_default_value = true
SHOPCONFIG_UID_FIELD.default_value = 0
SHOPCONFIG_UID_FIELD.type = 13
SHOPCONFIG_UID_FIELD.cpp_type = 3

SHOPCONFIG_NAME_FIELD.name = "name"
SHOPCONFIG_NAME_FIELD.full_name = ".dataconfig.ShopConfig.name"
SHOPCONFIG_NAME_FIELD.number = 2
SHOPCONFIG_NAME_FIELD.index = 1
SHOPCONFIG_NAME_FIELD.label = 2
SHOPCONFIG_NAME_FIELD.has_default_value = true
SHOPCONFIG_NAME_FIELD.default_value = ""
SHOPCONFIG_NAME_FIELD.type = 9
SHOPCONFIG_NAME_FIELD.cpp_type = 9

SHOPCONFIG_TYPE_FIELD.name = "type"
SHOPCONFIG_TYPE_FIELD.full_name = ".dataconfig.ShopConfig.type"
SHOPCONFIG_TYPE_FIELD.number = 3
SHOPCONFIG_TYPE_FIELD.index = 2
SHOPCONFIG_TYPE_FIELD.label = 2
SHOPCONFIG_TYPE_FIELD.has_default_value = true
SHOPCONFIG_TYPE_FIELD.default_value = 0
SHOPCONFIG_TYPE_FIELD.type = 13
SHOPCONFIG_TYPE_FIELD.cpp_type = 3

SHOPCONFIG_ID_FIELD.name = "id"
SHOPCONFIG_ID_FIELD.full_name = ".dataconfig.ShopConfig.id"
SHOPCONFIG_ID_FIELD.number = 4
SHOPCONFIG_ID_FIELD.index = 3
SHOPCONFIG_ID_FIELD.label = 2
SHOPCONFIG_ID_FIELD.has_default_value = true
SHOPCONFIG_ID_FIELD.default_value = 0
SHOPCONFIG_ID_FIELD.type = 13
SHOPCONFIG_ID_FIELD.cpp_type = 3

SHOPCONFIG_NUMBER_FIELD.name = "number"
SHOPCONFIG_NUMBER_FIELD.full_name = ".dataconfig.ShopConfig.number"
SHOPCONFIG_NUMBER_FIELD.number = 5
SHOPCONFIG_NUMBER_FIELD.index = 4
SHOPCONFIG_NUMBER_FIELD.label = 2
SHOPCONFIG_NUMBER_FIELD.has_default_value = true
SHOPCONFIG_NUMBER_FIELD.default_value = 0
SHOPCONFIG_NUMBER_FIELD.type = 13
SHOPCONFIG_NUMBER_FIELD.cpp_type = 3

SHOPCONFIG.name = "ShopConfig"
SHOPCONFIG.full_name = ".dataconfig.ShopConfig"
SHOPCONFIG.nested_types = {}
SHOPCONFIG.enum_types = {}
SHOPCONFIG.fields = {SHOPCONFIG_UID_FIELD, SHOPCONFIG_NAME_FIELD, SHOPCONFIG_TYPE_FIELD, SHOPCONFIG_ID_FIELD, SHOPCONFIG_NUMBER_FIELD}
SHOPCONFIG.is_extendable = false
SHOPCONFIG.extensions = {}
SHOPCONFIGARRAY_ITEMS_FIELD.name = "items"
SHOPCONFIGARRAY_ITEMS_FIELD.full_name = ".dataconfig.ShopConfigArray.items"
SHOPCONFIGARRAY_ITEMS_FIELD.number = 1
SHOPCONFIGARRAY_ITEMS_FIELD.index = 0
SHOPCONFIGARRAY_ITEMS_FIELD.label = 3
SHOPCONFIGARRAY_ITEMS_FIELD.has_default_value = false
SHOPCONFIGARRAY_ITEMS_FIELD.default_value = {}
SHOPCONFIGARRAY_ITEMS_FIELD.message_type = SHOPCONFIG
SHOPCONFIGARRAY_ITEMS_FIELD.type = 11
SHOPCONFIGARRAY_ITEMS_FIELD.cpp_type = 10

SHOPCONFIGARRAY.name = "ShopConfigArray"
SHOPCONFIGARRAY.full_name = ".dataconfig.ShopConfigArray"
SHOPCONFIGARRAY.nested_types = {}
SHOPCONFIGARRAY.enum_types = {}
SHOPCONFIGARRAY.fields = {SHOPCONFIGARRAY_ITEMS_FIELD}
SHOPCONFIGARRAY.is_extendable = false
SHOPCONFIGARRAY.extensions = {}

ShopConfig = protobuf.Message(SHOPCONFIG)
ShopConfigArray = protobuf.Message(SHOPCONFIGARRAY)

--[[Another parser, for the memory reason, use plain table struct 
instead of protobuf table! Auto generated, do not edit!!]]
shopconfig_x = {}
shopconfig_x.__index = shopconfig_x


--[[The class create method]]
function shopconfig_x.New()
    local self = {}
    setmetatable(self, shopconfig_x)
    self.items = {}
    return self
end


--[[The data parse method, input the protobuf data instance]]
function shopconfig_x:ParseData(protobufData)
    for k, v in ipairs(protobufData.items) do 
        local item = {}
        item.uid = v.uid
        item.name = v.name
        item.type = v.type
        item.id = v.id
        item.number = v.number
        table.insert(self.items, item)
    end
end


--[[Get the protobuf instance]]
function shopconfig_x:GetProtobuf()
    return ShopConfigArray()
end
