-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"


local FRIENDROOMCONFIG = protobuf.Descriptor();
local FRIENDROOMCONFIG_ID_FIELD = protobuf.FieldDescriptor();
local FRIENDROOMCONFIG_BASESCORE_FIELD = protobuf.FieldDescriptor();
local FRIENDROOMCONFIG_MINIMONEY_FIELD = protobuf.FieldDescriptor();
local FRIENDROOMCONFIGARRAY = protobuf.Descriptor();
local FRIENDROOMCONFIGARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();

FRIENDROOMCONFIG_ID_FIELD.name = "id"
FRIENDROOMCONFIG_ID_FIELD.full_name = ".dataconfig.FriendRoomConfig.id"
FRIENDROOMCONFIG_ID_FIELD.number = 1
FRIENDROOMCONFIG_ID_FIELD.index = 0
FRIENDROOMCONFIG_ID_FIELD.label = 2
FRIENDROOMCONFIG_ID_FIELD.has_default_value = true
FRIENDROOMCONFIG_ID_FIELD.default_value = 0
FRIENDROOMCONFIG_ID_FIELD.type = 13
FRIENDROOMCONFIG_ID_FIELD.cpp_type = 3

FRIENDROOMCONFIG_BASESCORE_FIELD.name = "baseScore"
FRIENDROOMCONFIG_BASESCORE_FIELD.full_name = ".dataconfig.FriendRoomConfig.baseScore"
FRIENDROOMCONFIG_BASESCORE_FIELD.number = 2
FRIENDROOMCONFIG_BASESCORE_FIELD.index = 1
FRIENDROOMCONFIG_BASESCORE_FIELD.label = 2
FRIENDROOMCONFIG_BASESCORE_FIELD.has_default_value = true
FRIENDROOMCONFIG_BASESCORE_FIELD.default_value = 0
FRIENDROOMCONFIG_BASESCORE_FIELD.type = 13
FRIENDROOMCONFIG_BASESCORE_FIELD.cpp_type = 3

FRIENDROOMCONFIG_MINIMONEY_FIELD.name = "miniMoney"
FRIENDROOMCONFIG_MINIMONEY_FIELD.full_name = ".dataconfig.FriendRoomConfig.miniMoney"
FRIENDROOMCONFIG_MINIMONEY_FIELD.number = 3
FRIENDROOMCONFIG_MINIMONEY_FIELD.index = 2
FRIENDROOMCONFIG_MINIMONEY_FIELD.label = 2
FRIENDROOMCONFIG_MINIMONEY_FIELD.has_default_value = true
FRIENDROOMCONFIG_MINIMONEY_FIELD.default_value = 0
FRIENDROOMCONFIG_MINIMONEY_FIELD.type = 13
FRIENDROOMCONFIG_MINIMONEY_FIELD.cpp_type = 3

FRIENDROOMCONFIG.name = "FriendRoomConfig"
FRIENDROOMCONFIG.full_name = ".dataconfig.FriendRoomConfig"
FRIENDROOMCONFIG.nested_types = {}
FRIENDROOMCONFIG.enum_types = {}
FRIENDROOMCONFIG.fields = {FRIENDROOMCONFIG_ID_FIELD, FRIENDROOMCONFIG_BASESCORE_FIELD, FRIENDROOMCONFIG_MINIMONEY_FIELD}
FRIENDROOMCONFIG.is_extendable = false
FRIENDROOMCONFIG.extensions = {}
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.name = "items"
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.full_name = ".dataconfig.FriendRoomConfigArray.items"
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.number = 1
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.index = 0
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.label = 3
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.has_default_value = false
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.default_value = {}
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.message_type = FRIENDROOMCONFIG
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.type = 11
FRIENDROOMCONFIGARRAY_ITEMS_FIELD.cpp_type = 10

FRIENDROOMCONFIGARRAY.name = "FriendRoomConfigArray"
FRIENDROOMCONFIGARRAY.full_name = ".dataconfig.FriendRoomConfigArray"
FRIENDROOMCONFIGARRAY.nested_types = {}
FRIENDROOMCONFIGARRAY.enum_types = {}
FRIENDROOMCONFIGARRAY.fields = {FRIENDROOMCONFIGARRAY_ITEMS_FIELD}
FRIENDROOMCONFIGARRAY.is_extendable = false
FRIENDROOMCONFIGARRAY.extensions = {}

FriendRoomConfig = protobuf.Message(FRIENDROOMCONFIG)
FriendRoomConfigArray = protobuf.Message(FRIENDROOMCONFIGARRAY)

--[[Another parser, for the memory reason, use plain table struct 
instead of protobuf table! Auto generated, do not edit!!]]
friendroomconfig_x = {}
friendroomconfig_x.__index = friendroomconfig_x


--[[The class create method]]
function friendroomconfig_x.New()
    local self = {}
    setmetatable(self, friendroomconfig_x)
    self.items = {}
    return self
end


--[[The data parse method, input the protobuf data instance]]
function friendroomconfig_x:ParseData(protobufData)
    for k, v in ipairs(protobufData.items) do 
        local item = {}
        item.id = v.id
        item.baseScore = v.baseScore
        item.miniMoney = v.miniMoney
        table.insert(self.items, item)
    end
end


--[[Get the protobuf instance]]
function friendroomconfig_x:GetProtobuf()
    return FriendRoomConfigArray()
end
