-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"


local NIUNIUTABLECONFIG = protobuf.Descriptor();
local NIUNIUTABLECONFIG_ID_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIG_POS1_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIG_POS2_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIG_POS3_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIG_POS4_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIG_POS5_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIG_POS6_FIELD = protobuf.FieldDescriptor();
local NIUNIUTABLECONFIGARRAY = protobuf.Descriptor();
local NIUNIUTABLECONFIGARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();

NIUNIUTABLECONFIG_ID_FIELD.name = "id"
NIUNIUTABLECONFIG_ID_FIELD.full_name = ".dataconfig.niuniutableconfig.id"
NIUNIUTABLECONFIG_ID_FIELD.number = 1
NIUNIUTABLECONFIG_ID_FIELD.index = 0
NIUNIUTABLECONFIG_ID_FIELD.label = 2
NIUNIUTABLECONFIG_ID_FIELD.has_default_value = true
NIUNIUTABLECONFIG_ID_FIELD.default_value = 0
NIUNIUTABLECONFIG_ID_FIELD.type = 13
NIUNIUTABLECONFIG_ID_FIELD.cpp_type = 3

NIUNIUTABLECONFIG_POS1_FIELD.name = "pos1"
NIUNIUTABLECONFIG_POS1_FIELD.full_name = ".dataconfig.niuniutableconfig.pos1"
NIUNIUTABLECONFIG_POS1_FIELD.number = 2
NIUNIUTABLECONFIG_POS1_FIELD.index = 1
NIUNIUTABLECONFIG_POS1_FIELD.label = 1
NIUNIUTABLECONFIG_POS1_FIELD.has_default_value = true
NIUNIUTABLECONFIG_POS1_FIELD.default_value = ""
NIUNIUTABLECONFIG_POS1_FIELD.type = 9
NIUNIUTABLECONFIG_POS1_FIELD.cpp_type = 9

NIUNIUTABLECONFIG_POS2_FIELD.name = "pos2"
NIUNIUTABLECONFIG_POS2_FIELD.full_name = ".dataconfig.niuniutableconfig.pos2"
NIUNIUTABLECONFIG_POS2_FIELD.number = 3
NIUNIUTABLECONFIG_POS2_FIELD.index = 2
NIUNIUTABLECONFIG_POS2_FIELD.label = 1
NIUNIUTABLECONFIG_POS2_FIELD.has_default_value = true
NIUNIUTABLECONFIG_POS2_FIELD.default_value = ""
NIUNIUTABLECONFIG_POS2_FIELD.type = 9
NIUNIUTABLECONFIG_POS2_FIELD.cpp_type = 9

NIUNIUTABLECONFIG_POS3_FIELD.name = "pos3"
NIUNIUTABLECONFIG_POS3_FIELD.full_name = ".dataconfig.niuniutableconfig.pos3"
NIUNIUTABLECONFIG_POS3_FIELD.number = 4
NIUNIUTABLECONFIG_POS3_FIELD.index = 3
NIUNIUTABLECONFIG_POS3_FIELD.label = 1
NIUNIUTABLECONFIG_POS3_FIELD.has_default_value = true
NIUNIUTABLECONFIG_POS3_FIELD.default_value = ""
NIUNIUTABLECONFIG_POS3_FIELD.type = 9
NIUNIUTABLECONFIG_POS3_FIELD.cpp_type = 9

NIUNIUTABLECONFIG_POS4_FIELD.name = "pos4"
NIUNIUTABLECONFIG_POS4_FIELD.full_name = ".dataconfig.niuniutableconfig.pos4"
NIUNIUTABLECONFIG_POS4_FIELD.number = 5
NIUNIUTABLECONFIG_POS4_FIELD.index = 4
NIUNIUTABLECONFIG_POS4_FIELD.label = 1
NIUNIUTABLECONFIG_POS4_FIELD.has_default_value = true
NIUNIUTABLECONFIG_POS4_FIELD.default_value = ""
NIUNIUTABLECONFIG_POS4_FIELD.type = 9
NIUNIUTABLECONFIG_POS4_FIELD.cpp_type = 9

NIUNIUTABLECONFIG_POS5_FIELD.name = "pos5"
NIUNIUTABLECONFIG_POS5_FIELD.full_name = ".dataconfig.niuniutableconfig.pos5"
NIUNIUTABLECONFIG_POS5_FIELD.number = 6
NIUNIUTABLECONFIG_POS5_FIELD.index = 5
NIUNIUTABLECONFIG_POS5_FIELD.label = 1
NIUNIUTABLECONFIG_POS5_FIELD.has_default_value = true
NIUNIUTABLECONFIG_POS5_FIELD.default_value = ""
NIUNIUTABLECONFIG_POS5_FIELD.type = 9
NIUNIUTABLECONFIG_POS5_FIELD.cpp_type = 9

NIUNIUTABLECONFIG_POS6_FIELD.name = "pos6"
NIUNIUTABLECONFIG_POS6_FIELD.full_name = ".dataconfig.niuniutableconfig.pos6"
NIUNIUTABLECONFIG_POS6_FIELD.number = 7
NIUNIUTABLECONFIG_POS6_FIELD.index = 6
NIUNIUTABLECONFIG_POS6_FIELD.label = 1
NIUNIUTABLECONFIG_POS6_FIELD.has_default_value = true
NIUNIUTABLECONFIG_POS6_FIELD.default_value = ""
NIUNIUTABLECONFIG_POS6_FIELD.type = 9
NIUNIUTABLECONFIG_POS6_FIELD.cpp_type = 9

NIUNIUTABLECONFIG.name = "niuniutableconfig"
NIUNIUTABLECONFIG.full_name = ".dataconfig.niuniutableconfig"
NIUNIUTABLECONFIG.nested_types = {}
NIUNIUTABLECONFIG.enum_types = {}
NIUNIUTABLECONFIG.fields = {NIUNIUTABLECONFIG_ID_FIELD, NIUNIUTABLECONFIG_POS1_FIELD, NIUNIUTABLECONFIG_POS2_FIELD, NIUNIUTABLECONFIG_POS3_FIELD, NIUNIUTABLECONFIG_POS4_FIELD, NIUNIUTABLECONFIG_POS5_FIELD, NIUNIUTABLECONFIG_POS6_FIELD}
NIUNIUTABLECONFIG.is_extendable = false
NIUNIUTABLECONFIG.extensions = {}
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.name = "items"
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.full_name = ".dataconfig.niuniutableconfigArray.items"
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.number = 1
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.index = 0
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.label = 3
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.has_default_value = false
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.default_value = {}
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.message_type = NIUNIUTABLECONFIG
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.type = 11
NIUNIUTABLECONFIGARRAY_ITEMS_FIELD.cpp_type = 10

NIUNIUTABLECONFIGARRAY.name = "niuniutableconfigArray"
NIUNIUTABLECONFIGARRAY.full_name = ".dataconfig.niuniutableconfigArray"
NIUNIUTABLECONFIGARRAY.nested_types = {}
NIUNIUTABLECONFIGARRAY.enum_types = {}
NIUNIUTABLECONFIGARRAY.fields = {NIUNIUTABLECONFIGARRAY_ITEMS_FIELD}
NIUNIUTABLECONFIGARRAY.is_extendable = false
NIUNIUTABLECONFIGARRAY.extensions = {}

niuniutableconfig = protobuf.Message(NIUNIUTABLECONFIG)
niuniutableconfigArray = protobuf.Message(NIUNIUTABLECONFIGARRAY)

--[[Another parser, for the memory reason, use plain table struct 
instead of protobuf table! Auto generated, do not edit!!]]
niuniutableconfig_x = {}
niuniutableconfig_x.__index = niuniutableconfig_x


--[[The class create method]]
function niuniutableconfig_x.New()
    local self = {}
    setmetatable(self, niuniutableconfig_x)
    self.items = {}
    return self
end


--[[The data parse method, input the protobuf data instance]]
function niuniutableconfig_x:ParseData(protobufData)
    for k, v in ipairs(protobufData.items) do 
        local item = {}
        item.id = v.id
        if v:HasField("pos1") then 
            item.pos1 = v.pos1
        end
        if v:HasField("pos2") then 
            item.pos2 = v.pos2
        end
        if v:HasField("pos3") then 
            item.pos3 = v.pos3
        end
        if v:HasField("pos4") then 
            item.pos4 = v.pos4
        end
        if v:HasField("pos5") then 
            item.pos5 = v.pos5
        end
        if v:HasField("pos6") then 
            item.pos6 = v.pos6
        end
        table.insert(self.items, item)
    end
end


--[[Get the protobuf instance]]
function niuniutableconfig_x:GetProtobuf()
    return niuniutableconfigArray()
end
