//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class XYHY_ResourceMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(XYHY.ResourceMgr), typeof(System.Object));
		L.RegFunction("Initialize", Initialize);
		L.RegFunction("UnInitialize", UnInitialize);
		L.RegFunction("LoadTextureSync", LoadTextureSync);
		L.RegFunction("LoadImmortalTextureSync", LoadImmortalTextureSync);
		L.RegFunction("LoadAtlasSync", LoadAtlasSync);
		L.RegFunction("LoadNormalObjSync", LoadNormalObjSync);
		L.RegFunction("LoadSceneResidentMemoryObjSync", LoadSceneResidentMemoryObjSync);
		L.RegFunction("LoadResidentMemoryObjSync", LoadResidentMemoryObjSync);
		L.RegFunction("LoadNormalObjAsync", LoadNormalObjAsync);
		L.RegFunction("LoadResidentMemoryObjAsync", LoadResidentMemoryObjAsync);
		L.RegFunction("LoadConfigFile", LoadConfigFile);
		L.RegFunction("UnloadResource", UnloadResource);
		L.RegFunction("UnloadImmortalResource", UnloadImmortalResource);
		L.RegFunction("UnloadAllNormalResources", UnloadAllNormalResources);
		L.RegFunction("UnloadLastSceneAsset", UnloadLastSceneAsset);
		L.RegFunction("LoadInEditor", LoadInEditor);
		L.RegFunction("LoadFromResource", LoadFromResource);
		L.RegFunction("LoadFromAssetBundle", LoadFromAssetBundle);
		L.RegFunction("LoadGameDep", LoadGameDep);
		L.RegFunction("New", _CreateXYHY_ResourceMgr);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateXYHY_ResourceMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				XYHY.ResourceMgr obj = new XYHY.ResourceMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: XYHY.ResourceMgr.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			obj.Initialize();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnInitialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			obj.UnInitialize();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadTextureSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Texture2D o = obj.LoadTextureSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadImmortalTextureSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Texture2D o = obj.LoadImmortalTextureSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAtlasSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UIAtlas o = obj.LoadAtlasSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadNormalObjSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadNormalObjSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSceneResidentMemoryObjSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadSceneResidentMemoryObjSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadResidentMemoryObjSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadResidentMemoryObjSync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadNormalObjAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			bool o = obj.LoadNormalObjAsync(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadResidentMemoryObjAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			AssetBundleParams arg0 = (AssetBundleParams)ToLua.CheckObject(L, 2, typeof(AssetBundleParams));
			UnityEngine.Object o = obj.LoadResidentMemoryObjAsync(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadConfigFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			byte[] o = obj.LoadConfigFile(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			System.Type arg1 = (System.Type)ToLua.CheckObject(L, 3, typeof(System.Type));
			bool o = obj.UnloadResource(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadImmortalResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			System.Type arg1 = (System.Type)ToLua.CheckObject(L, 3, typeof(System.Type));
			bool o = obj.UnloadImmortalResource(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadAllNormalResources(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			obj.UnloadAllNormalResources();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadLastSceneAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			XYHY.ResourceMgr obj = (XYHY.ResourceMgr)ToLua.CheckObject(L, 1, typeof(XYHY.ResourceMgr));
			string arg0 = ToLua.CheckString(L, 2);
			UILabel arg1 = (UILabel)ToLua.CheckUnityObject(L, 3, typeof(UILabel));
			obj.UnloadLastSceneAsset(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadInEditor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			System.Type arg1 = (System.Type)ToLua.CheckObject(L, 2, typeof(System.Type));
			UnityEngine.Object o = XYHY.ResourceMgr.LoadInEditor(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadFromResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			UnityEngine.Object o = XYHY.ResourceMgr.LoadFromResource(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadFromAssetBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			UnityEngine.Object o = XYHY.ResourceMgr.LoadFromAssetBundle(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadGameDep(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			System.Action arg1 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (System.Action)ToLua.CheckObject(L, 2, typeof(System.Action));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg1 = DelegateFactory.CreateDelegate(typeof(System.Action), func) as System.Action;
			}

			XYHY.ResourceMgr.LoadGameDep(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

